### ISSUE TITLE
是否考虑支持ES6？

### ISSUE THREAD

**Issue by billgo** [jf3096/zhihu-particle#1]
我看到可读源码是用 Typescript 来写的，是否有考虑过再用 ES6 来写一篇呢？ 这样即便别人不了解 Typescript 也能阅读你读源码，从中掌握使用方法。

**Comment by jf3096** [comment]
恩  谢谢你的意见, 今天之内完成, 其实对于typescript来说, 我只需要改一下tsconfig的参数变成es6即可.

**Comment by billgo** [comment]
@jf3096 反馈果然很快，值得表扬。对于使用来说影响并不大，但是对于想要了解更多的童鞋来说，支持多一种写法应该会更好，毕竟用 ES6 的人还是占大多数的。嘿嘿

**Comment by jf3096** [comment]
提供了一个es6的分支
