### ISSUE TITLE
请问可以单独使用不依赖react吗

### ISSUE THREAD

**Issue by zuoliang0** [jf3096/zhihu-particle#2]
请问可以单独使用不依赖react吗

**Comment by jf3096** [comment]
当然可以呀 老铁

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Sean Zhang <notifications@github.com>
发送时间: Tuesday, July 30, 2019 6:27:35 PM
收件人: jf3096/zhihu-particle <zhihu-particle@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [jf3096/zhihu-particle] 请问可以单独使用不依赖react吗 (#2)


请问可以单独使用不依赖react吗

―
